# Generated by Django 3.2.8 on 2021-11-14 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=32)),
                ('class_time', models.CharField(max_length=32)),
                ('class_type', models.CharField(blank=True, max_length=32, null=True)),
                ('class_level', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'verbose_name_plural': 'Classes',
            },
        ),
    ]
